export enum ErrorCode{
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
    USER_NOT_FOUND="USER_NOT_FOUND",
    INVALID_OTP = "INVALID_OTP",
    EXPIRED_OTP = "EXPIRED_OTP",
    UNAUTHORIZED = "UNAUTHORIZED",
    VALIDATION_ERROR = "VALIDATION_ERROR",
    UNKNOWN_ERROR = "UNKNOWN_ERROR",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    FORBIDDEN= "Insufficient permissions",
    INTERNAL_ERROR= "Internal server error",
    DATABASE_ERROR="Database Error",
    NOT_FOUND="Not Found"
}